# Stubs for psycopg2 (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

def connect(dsn: Optional[Any] = ..., connection_factory: Optional[Any] = ..., cursor_factory: Optional[Any] = ..., **kwargs: Any): ...
