# Stubs for psycopg2.extensions (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any, Optional

ISOLATION_LEVEL_AUTOCOMMIT: int
ISOLATION_LEVEL_READ_UNCOMMITTED: int
ISOLATION_LEVEL_READ_COMMITTED: int
ISOLATION_LEVEL_REPEATABLE_READ: int
ISOLATION_LEVEL_SERIALIZABLE: int
ISOLATION_LEVEL_DEFAULT: Any
STATUS_SETUP: int
STATUS_READY: int
STATUS_BEGIN: int
STATUS_SYNC: int
STATUS_ASYNC: int
STATUS_PREPARED: int
STATUS_IN_TRANSACTION = STATUS_BEGIN
POLL_OK: int
POLL_READ: int
POLL_WRITE: int
POLL_ERROR: int
TRANSACTION_STATUS_IDLE: int
TRANSACTION_STATUS_ACTIVE: int
TRANSACTION_STATUS_INTRANS: int
TRANSACTION_STATUS_INERROR: int
TRANSACTION_STATUS_UNKNOWN: int

def register_adapter(typ: Any, callable: Any) -> None: ...

class SQL_IN:
    def __init__(self, seq: Any) -> None: ...
    def prepare(self, conn: Any) -> None: ...
    def getquoted(self): ...

class NoneAdapter:
    def __init__(self, obj: Any) -> None: ...
    def getquoted(self, _null: bytes = ...): ...

def make_dsn(dsn: Optional[Any] = ..., **kwargs: Any): ...

JSON: Any
JSONARRAY: Any
JSONB: Any
JSONBARRAY: Any
k: Any
