# Stubs for psycopg2.tests (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .testconfig import dsn
from .testutils import unittest

def test_suite(): ...
