# Stubs for psycopg2.tests.test_bug_gc (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .testutils import ConnectingTestCase, skip_if_no_uuid

class StolenReferenceTestCase(ConnectingTestCase):
    def test_stolen_reference_bug(self): ...

def test_suite(): ...
