# Stubs for psycopg2.tests.test_errcodes (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .testutils import ConnectingTestCase, slow, unittest

class ErrocodeTests(ConnectingTestCase):
    def test_lookup_threadsafe(self) -> None: ...

def test_suite(): ...
