# Stubs for psycopg2.tests.test_bugX000 (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

import unittest

class DateTimeAllocationBugTestCase(unittest.TestCase):
    def test_date_time_allocation_bug(self) -> None: ...

def test_suite(): ...
