# Stubs for psycopg2.tests.testconfig (Python 3.7)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from typing import Any

dbname: Any
dbhost: Any
dbport: Any
dbuser: Any
dbpass: Any
green: Any
dsn: Any
repl_dsn: Any
repl_dsn = dsn
repl_slot: Any
